language: java
install: true

addons:
  sonarcloud:
    organization: "guillaumewaignier-github"
    token:
      secure: "faMXktVO8Kq/bmzES8SdBl8gFF01BqC4Um69xN+XimFpIXtkPG6CnwbUzfN6Jo1fD06lRKHjq3fjSc7Nj3hvpxAty+fNoHJumNnGMoDJy2K+5zJ7fQOJ7Zmly/dacq1NB+01fQeEwkftUvy91Khc/iR3k8nIK8TPliGKwmjWh8fgmCxdCfaIPSTcRdVexZZrRWw9yTfLaAJ/ZIAdEKjE52vQmP6iKDWqbkyCNHmitxwJzXEsgrvxBqHvNdEoAD0Zmz03EBvPuM4v9YN9EqRJB66bNc4O0NAb6+hU314WU7sWvYDnkzgGDG8yYG0APbYA+b/g7rWM+LlHqw40zS6B2uywrjiBjJwuzRLr7HH/sGHziik00dGQoJ6U+4YOIo8qukfAQzzZXH2NMLUBxRWmZVLSIhsDTVt6IwpaHkE2DUWeMRmtWKZsYGudiTjBGLY8GfEak4x3Pg5/jxBMJft6yJN0d7mDYW4Wi5SZl9f3R0vwbUhMaWAYdw3KM3HUHzSwVOQuPPkHJiCNeadMYWnAWKNRfpjatzZ9sbycSGoM3mBBA3TCMgQZJLujO0sUVw147GXPbP68Z0Ft6Mf0Syul8WNnOjMWmYmK2qP4v9f9yX8w0vOWRRtI/bwkJ5J6lSpCWkt87KnF7LXyz0QcTnCiD0y/Zm4csXK3w1J1HiFww58="

jdk:
  - oraclejdk8

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/v0.7.26/install.sh | sudo bash"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar
  - fossa init
  - fossa analyze

deploy:
  provider: releases
  api_key:
    secure: Edy32MeLRfwAzp6RGVI8Yc48URPhAXbAqiPp5SdGUdZRT41DN0bXI8cNT7fVgmdxYTfiLUxOs85GQKWkUQFzpLKOWNYKwbemdBDlJmgjL93+H4IwU5OApnIvnWDMoKNU8EjgaB7KgvwFpFpUsnZq86J0tNB+g64TuU+JemK1Pvn3ozevIECaglcCbitJmb1YRyLgZF0Tuz6DOXYCD7oZ2pGsakQWBe0PynGQw8Sov45IMXY4298RSOikCrqsZ3DngidXMs/L/An3rSi3wZwXTeJ2VcC3Lj9xEPYrIi8WErc9kg3F3qL1vTtxIIVn3ZCd/RT0AI8+G/HVBBWJLdNVRmp2xUge4YSlU8jcwhpdxYPw/fI7Wm5JwCKDBy8KOHew+k3ei++WWQYhe8QlKepeQh44aSQUQjhdMZncW2cEpaqMX+GvADOV3k73+AYO41Cbc7T2PkwhCxHDANO+We/sOIIGn85SOwQgb0LArufF3qW49TU/vKCRg7Yeh74ZNh97QjGc5wEiiMz2ckuMC+SX7J8du4cupA0u+g7kbg3kEsnw8Au9/7JrbMYA6LVfAkk5VoTxmKaYehqYBAihzV6h8jNnM6g5U07hp/HTEfr0c1iXplJS6P+xJyb2Zgn91VbIoOUh4gU7FZxmW1ZPVuEzhbgbruqisLRfjzonwSEdlD8=
  file: target/consumer-offset-exporter-*-bin.tar.gz
  draft: true
  skip_cleanup: true
  on:
    tags: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
