language: java
install: true

addons:
  sonarcloud:
    organization: "guillaumewaignier-github"
    token:
      secure: "faMXktVO8Kq/bmzES8SdBl8gFF01BqC4Um69xN+XimFpIXtkPG6CnwbUzfN6Jo1fD06lRKHjq3fjSc7Nj3hvpxAty+fNoHJumNnGMoDJy2K+5zJ7fQOJ7Zmly/dacq1NB+01fQeEwkftUvy91Khc/iR3k8nIK8TPliGKwmjWh8fgmCxdCfaIPSTcRdVexZZrRWw9yTfLaAJ/ZIAdEKjE52vQmP6iKDWqbkyCNHmitxwJzXEsgrvxBqHvNdEoAD0Zmz03EBvPuM4v9YN9EqRJB66bNc4O0NAb6+hU314WU7sWvYDnkzgGDG8yYG0APbYA+b/g7rWM+LlHqw40zS6B2uywrjiBjJwuzRLr7HH/sGHziik00dGQoJ6U+4YOIo8qukfAQzzZXH2NMLUBxRWmZVLSIhsDTVt6IwpaHkE2DUWeMRmtWKZsYGudiTjBGLY8GfEak4x3Pg5/jxBMJft6yJN0d7mDYW4Wi5SZl9f3R0vwbUhMaWAYdw3KM3HUHzSwVOQuPPkHJiCNeadMYWnAWKNRfpjatzZ9sbycSGoM3mBBA3TCMgQZJLujO0sUVw147GXPbP68Z0Ft6Mf0Syul8WNnOjMWmYmK2qP4v9f9yX8w0vOWRRtI/bwkJ5J6lSpCWkt87KnF7LXyz0QcTnCiD0y/Zm4csXK3w1J1HiFww58="

jdk:
  - openjdk11

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/v0.7.26/install.sh | sudo bash"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar
  - docker build . -t $TRAVIS_COMMIT

deploy:
  - provider: releases
    api_key:
      secure: QeU5qFeM+/2ZQbgYNsHGBm4tglO+gsbw27uvUljjAx5jrEmjZxeihF8KuCepjYyuS/DlKlFYXcHJWi/bBYRUWKjVxMzOWs1eMQRY5GPcmQoDNjO881dr8w1pqb8JEImeR6C0g3iwG314Pto2LasMgCile7EYdzzhDB8hXsN4cXKB3ED7hyAbbs9gdkrG0ac9XKFHXRx7fBYZ+YVMy3n9bF7+/5M2Br2fokTdNL//kBhr4B8jTuLBh4JHKCnZScw8vgH9uqYWGEaAja4VY9KZqTo0ML3mVMdlmx46vvYHdnvjDe1ND+Hzxyi7ycq5BvXSBA3R++FffJ4cOdWYbA0vmaGtxpJ3yMSoxWKYApWCeEypn1UdY7IcKNfC8u8LBNv4Au3Z3AXf6B/ZEfx5oh3UaodEI4QxKCUS0O70Aa/bb97q8JjqJSKFg1g7dF/rppS8nnt9ptcXxR9mRy8EXjgTfmXouh44mXNeyrqVysQdvvcZB06tqsHv/+Eoyp0u9JsxwCmgdWiczFIaJ19geCVNf8C1qtnuba0Jm3iHaQq7NnOD24gWzzfyd7jxI37nEPqxuQyMzJJIWqMbdX1RYZS+gV8tlHaNZ6AczVbrXphjd8MWnFS4z+OBA6ieEk7wvbPAbzlhHLbTmXK/Ww8oh1Txt754i8FTqlcpXBrv/brD+Aw=
    file: target/consumer-offset-exporter-*-bin.tar.gz
    prerelease: true
    draft: true
    name: "$TRAVIS_TAG"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash docker_push.sh $TRAVIS_BRANCH
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: bash docker_push.sh latest
    on:
      branch: master


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
