lowercaseOutputName: true

rules:
- pattern: kafka.consumer<type=ConsumerOffset, groupId=(.+), topic=(.+), partition=(.*)><>Value
  name: kafka_consumer_consumeroffset
  type: GAUGE
  labels:
    groupid: "$1"
    topic: "$2"
    partition: "$3"
