# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: test
on:
  push:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: compute
      id: compute
      run: echo "::set-output name=test::hello"
      
    - name: show
      run: echo ${{ steps.compute.outputs.test }}
    
